name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: 9
        source-url: https://nuget.pkg.github.com/dev-osrose/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Create Package
      run: dotnet pack --configuration Release Revise
    - name: Publish
      run: dotnet nuget push "Revise/bin/Release/Revise.*.nupkg" --skip-duplicate --no-symbols true -k ${{secrets.GITHUB_TOKEN}}
      env:
        DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: 0
